version: '3.8'

services:
  nginx:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    network_mode: host
    restart: unless-stopped
    environment:
      - FRONTEND_HOST=${FRONTEND_HOST:-host.docker.internal}
      - FRONTEND_PORT=${FRONTEND_PORT:-3000}
      - BACKEND_HOST=${BACKEND_HOST:-host.docker.internal}
      - BACKEND_PORT=${BACKEND_PORT:-8000}